-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Servidor: 127.0.0.1
-- Tiempo de generación: 14-11-2022 a las 22:39:30
-- Versión del servidor: 10.4.24-MariaDB
-- Versión de PHP: 8.1.6

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de datos: `db_cine`
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `peliculas`
--

CREATE TABLE `peliculas` (
  `id` int(11) NOT NULL,
  `titulo` varchar(40) NOT NULL,
  `duracion` int(3) NOT NULL,
  `anio` int(4) NOT NULL,
  `imagen` varchar(500) NOT NULL,
  `sinopsis` varchar(500) NOT NULL,
  `video` varchar(500) NOT NULL,
  `director` varchar(40) NOT NULL,
  `elenco` varchar(150) NOT NULL,
  `id_genero` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Volcado de datos para la tabla `peliculas`
--

INSERT INTO `peliculas` (`id`, `titulo`, `duracion`, `anio`, `imagen`, `sinopsis`, `video`, `director`, `elenco`, `id_genero`) VALUES
(1, 'El Conjuro 2', 134, 2016, 'uploads/634b47cdaedeb6.12614413.jpg', 'Secuela de la exitosa «Expediente Warren» (2013), que lleva de nuevo a la pantalla otro caso real de los expedientes de los renombrados demonólogos Ed y Lorraine Warren. En este caso ambos viajarán al norte de Londres para ayudar a una madre soltera que tiene a su cargo cuatro hijos y que vive sola con ellos en una casa plagada de espíritus malignos.', 'uploads/634b47cdaf2e33.39847882.mp4', 'James Wan', 'Abhi Sinha, Annie Young, Benjamin Haigh, Bob Adrian.', 1),
(8, 'Inseparables', 104, 2016, 'uploads/634c0fe9487898.37702399.jpg', 'Un adinerado hombre de negocios con tetraplejia contrata a un jardinero impulsivo como su asistente terapéutico. Basada en hechos reales.', 'uploads/634c0fe948dab1.53374936.mp4', 'Marcos Carnevale', 'Oscar Martínez,Rodrigo de la Serna,Alejandra Flechner', 2),
(9, 'Nobody', 92, 2021, 'uploads/634c102038e605.23529347.jpg', 'Hutch Mansell, un padre de familia que aguanta con resignación y sin defenderse los golpes de la vida. Un don nadie. Una noche, cuando dos ladrones entran en su casa, Hutch decide no actuar y no trata de defenderse ni al él mismo ni a su familia, convencido de que solo así evitará una escalada de violencia. Tras el ataque, su hija adolescente Blake no oculta su decepción, y su esposa Becca se aleja todavía más.', 'uploads/634c10203933a8.17505163.mp4', 'Ilya Naishuller', 'Alain Moussi, Alan Wong, Aleksandr Pal, Aleksey Serebryakov', 3),
(10, 'The Batman', 176, 2022, 'uploads/634c1045257a89.57702278.jpg', 'Cuando un asesino se dirige a la élite de Gotham con una serie de maquinaciones sádicas, un rastro de pistas crípticas envía Batman a una investigación en los bajos fondos. A medida que las pruebas comienzan a acercarse a su casa y se hace evidente la magnitud de los planes del autor, Batman debe forjar nuevas relaciones, desenmascarar al culpable y hacer justicia al abuso de poder y la corrupción que durante mucho tiempo han asolado Gotham City.', 'uploads/634c104525cde6.12670099.mp4', 'Bradley Parker', 'Robert Pattinson, Adam Rojko Vega, Albert Giannitelli, Alex Ferns, Alfredo Tavares,', 3),
(11, 'Django unchained', 165, 2012, 'uploads/634c10663ac284.53243432.jpg', 'En Texas, dos años antes de estallar la Guerra Civil Americana, King Schultz (Christoph Waltz), un cazarrecompensas alemán que sigue la pista a unos asesinos para cobrar por sus cabezas, le promete al esclavo negro Django (Jamie Foxx) dejarlo en libertad si le ayuda a atraparlos. Él acepta, pues luego quiere ir a buscar a su esposa Broomhilda (Kerry Washington), esclava en una plantación del terrateniente Calvin Candie (Leonardo DiCaprio).', 'uploads/634c10663b17c9.22469341.mp4', 'Quentin Tarantino', 'Jamie Foxx, Christoph Waltz, Leonardo DiCaprio, Kerry Washington', 4),
(12, 'El curioso caso de Benjamin Button', 146, 2008, 'uploads/634c10931b8131.90687229.jpg', 'David Fincher dirige este relato ganador del Óscar, en el que Benjamin Button, un hombre que nació viejo y arrugado, rejuvenece a medida que pasan los años.', 'uploads/634c10931bd0b2.97169076.mp4', 'David Fincher', 'Brad Pitt,Cate Blanchett,Taraji P. Henson', 4),
(13, 'El Gran Gatsby', 143, 2013, 'uploads/634c10be1064d6.82609122.jpg', 'Nueva York, años 20. En la alta sociedad norteamericana, llama la atención la presencia de Jay Gatsby, un hombre misterioso e inmensamente rico, al que todos consideran un advenedizo, lo que no impide que acudan a sus fastuosas fiestas en su gran mansión de Long Island. Gatsby vive obsesionado con la idea de recuperar al amor que dejó escapar años atrás. Para ello se hará amigo de su vecino recién llegado, el joven Nick Carraway.', 'uploads/634c10be10cfe3.20370814.mp4', 'Baz Luhrmann', 'Leonardo DiCaprio, Tobey Maguire, Carey Mulligan, Joel Edgerton, Isla Fisher', 5),
(14, 'Luca', 101, 2021, 'uploads/634b404b8ecbf4.99524506.jpg', 'Ambientada en un precioso pueblo costero de la Riviera italiana, narra la historia sobre el paso a la edad adulta de un chico que vive un verano inolvidable lleno de helados, pasta e infinitos paseos en scooter. Luca comparte estas aventuras con su nuevo mejor amigo, pero toda la diversión se ve amenazada por un secreto muy profundo: él es un monstruo marino de un mundo que yace bajo la superficie del agua.', 'uploads/634b404b8f00e3.03668977.mp4', 'Enrico Casarosa', 'Emma Berman, Jack Dylan Grazer, Jacob Tremblay, Jim Gaffigan.', 6),
(16, 'La invitación', 105, 2022, 'uploads/634c10f203e124.94860659.jpg', 'Una joven es cortejada y deslumbrada solo para descubrir que una conspiración gótica está en marcha.', 'uploads/634c10f2044a73.92353675.mp4', 'Jessica M. Thompson', 'Alana Boden, Carol Ann Crawford, Christine Grace Szarko, Courtney Taylor,', 1),
(17, 'Nope', 130, 2022, 'uploads/634c111b064459.07975229.jpg', 'Dos rancheros de un remoto pueblo del interior de California hacen un descubrimiento tan insólito como escalofriante.', 'uploads/634c111b066726.32545498.mp4', 'Jordan Peele', '	 Daniel Kaluuya Keke Palmer Steven Yeun Michael Wincott', 1),
(19, 'El señor de los anillos: La comunidad de', 180, 2001, 'uploads/634c11464ec9f6.22453420.jpg', 'En la Tierra Media, el Señor Oscuro Saurón creó los Grandes Anillos de Poder, forjados por los herreros Elfos. Tres para los reyes Elfos, siete para los Señores Enanos, y nueve para los Hombres Mortales. Secretamente, Saurón también forjó un anillo maestro, el Anillo Único, que contiene en sí el poder para esclavizar a toda la Tierra Media. Con la ayuda de un grupo de amigos y de valientes aliados, Frodo emprende un peligroso viaje con la misión de destruir el Anillo Único. Pero el Señor Oscuro.', 'uploads/634c11464f13c2.96038985.mp4', 'Peter Jackson', 'Alan Howard, Andy Serkis, Billy Boyd, Brent McIntyre.', 12),
(20, 'La mujer rey', 135, 2022, 'uploads/634b4b7cead9a2.79270661.jpg', 'Una epopeya histórica inspirada en los hechos reales que sucedieron en el Reino de Dahomey, uno de los estados más poderosos de África en los siglos XVIII y XIX. La historia sigue a Nanisca (Davis), general de la unidad militar exclusivamente femenina y a Nawi (Mbedu), una recluta ambiciosa. Juntas lucharon contra enemigos que violaron su honor, esclavizaron a su gente y amenazaron con destruir todo por lo que habían vivido.', 'uploads/634b4b7ceb3429.40868108.mp4', 'Gina Prince-Bythewood', 'Adrienne Warren, Angélique Kidjo, Chioma Antoinette Umeala, Hero Fiennes-Tiffin.', 3),
(21, 'El teléfono del señor Harrigan', 106, 2022, 'uploads/634c8847bc4a76.17566292.jpg', 'Un chico entabla amistad con un anciano y huraño multimillonario y descubre que es capaz de comunicarse con él después de muerto gracias al iPhone con el que fue enterrado. Basada en el relato corto de Stephen King.', 'uploads/634c8847bc9210.91960210.mp4', 'John Lee Hancock', 'Alexa Shae Niziak, Bennett Saltzman, Caitlin Shorey, Colin O\Brien, Conor William Wright, Cyrus Arnold, Daniel Reece, Donald Sutherland, Frank Ridley,', 1),
(22, 'Hellraiser', 121, 2022, 'uploads/634c8b79c96127.01709104.jpg', 'Una joven que lucha contra la adicción se apodera de una antigua caja de rompecabezas, sin saber que su propósito es convocar a los Cenobitas, un grupo de sádicos seres sobrenaturales de otra dimensión.', 'uploads/634c8b79cbece1.44400532.mp4', ' David Bruckner', ' Adam Faison, Aoife Hinds, Brandon Flynn, Drew Starkey, Goran Visnjic, Gorica Regodić, Greg De Cuir, Hiam Abbass, Ivona Kustudic, Jamie Clayton, Jason', 1),
(23, 'Jeepers Creepers: Reborn', 88, 2022, 'uploads/634cba6c479171.49667433.jpg', '\r\nEl Horror Hound festival celebra su primer evento en Luisiana, donde atrae a cientos de fanes del terror; entre ellos se encuentra Laine que, obligada a asistir por Chase, su novio, comienza a experimentar premoniciones inexplicables y visiones inquietantes relacionadas con el pasado de la ciudad y con El Creeper. A medida que avanza el festival y el entretenimiento empapado de sangre se convierte en un frenesí, Laine cree que algo sobrenatural ha sido convocado y que ella está en el centro de', 'uploads/634cba6c47ec01.16893281.mp4', 'Timo Vuorensola', 'Alexander Halsall, Colin Murtagh, Dee Wallace, Gabriel Freilich, Gary Graham, Georgia Goodman, Helen Lauren, Imran Adams, Jarreau Benjamin, Jodie Mcmu', 1),
(24, 'Smile', 115, 2022, 'uploads/634c8ef1191bc2.72575522.jpg', 'Tras presenciar un extraño y traumático incidente con un paciente, la doctora Rose Cotter (Sosie Bacon) comienza a experimentar sucesos aterradores que no puede explicar. A medida que un miedo sobrecogedor comienza a afectar a todos los aspectos de su vida, Rose se verá obligada a afrontar a su problemático pasado para sobrevivir y escapar de su terrorífica nueva realidad.', 'uploads/634c8ef1195c98.69240747.mp4', 'Parker Finn', 'Asia Hernandez, Athena Smiley, Bob Leszczak, Brandon Brigman, Caitlin Stasey, Dora Kiss, Felix Melendez Jr., Gillian Zinser, Ilene Blackman, Jared Joh', 1),
(25, 'The Medium', 131, 2021, 'uploads/634c9133eb4723.68265803.jpg', 'Una historia espantosa sobre la herencia de un chamán en la región de Isan en Tailandia y lo que podría estar poseyendo a un miembro de la familia, podría no ser la Diosa que pretende ser.', 'uploads/634c9133ebab74.27757624.mp4', 'Banjong Pisanthanakun', 'Akkaradech Rattanawong, Arunee Wattana, Boonsong Nakphoo, Chatchawat Sanveang, Narilya Gulmongkolpech, Pakapol Srirongmuang, Sawanee Utoomma, Sirani Y', 1),
(26, 'Scream', 120, 2022, 'uploads/634c932f5faf33.89572891.jpg', 'Una nueva entrega de la saga de terror ‘Scream’ que seguirá a una mujer que regresa a su ciudad natal para intentar descubrir quién ha estado cometiendo una serie de crímenes atroces.', 'uploads/634c932f6044d4.92414237.mp4', 'Kara McGee, Matt Bettinelli-Olpin, Scott', 'Chester Tam, Courteney Cox, David Arquette, Dylan Minnette, Heather Matarazzo, Jack Quaid, Jasmin Savoy Brown, Jenna Ortega, Kyle Gallner, Marley Shel', 1),
(27, 'Paranormal Activity: Next of Kin', 98, 2021, 'uploads/634c95239819e9.52100679.jpg', 'Margot, una directora de documentales, se dirige a una comunidad amish aislada con la esperanza de saber algo de su madre y su familia perdida hace tiempo. Tras una serie de extraños sucesos y descubrimientos, se da cuenta de que esta comunidad puede no ser lo que parece.', 'uploads/634c95239838a3.27534679.mp4', 'Rob Burgess, Shane B. Scott, William Eub', 'Colin Keane, Dan Lippert, Emerald Rose Sullivan, Emily Bader, Henry Ayres-Brown, Kyli Zion, Roland Buck III, Wesley Han', 1),
(28, 'The Ex', 90, 2021, 'uploads/634c981b707248.74130765.jpg', 'La historia de cómo las redes sociales y la mensajería instantánea están cambiando la vida de una persona moderna. Han pasado varios años desde que un adolescente de 16 años publicó una foto de su novia en el chat general, con la esperanza de presumir ante sus amigos. Ahora tiene una vida adulta feliz: trabajo, amigos, su prometida Katya, que está a punto de convertirse en su esposa. Pero Internet le hace recordar el amor adolescente, tras el cual se produce una cadena de inexplicables acontecim', 'uploads/634c981b70a849.88652467.mp4', 'Evgeny Puzyrevsky', 'Anna Osipova, Elena Morozova, Konstantin Beloshapka, Oleg Dulenin, Pavel Golubev, Sergey Dvoynikov, Vera Kincheva, Vladimir Seleznyov, Yekaterina Shum', 1),
(29, '30 noches con mi ex', 95, 2022, 'uploads/634c9a2b82c4b4.07159064.jpg', 'Turbo, luego de años de separado de la Loba, acepta, por pedido de la hija que tienen en común, convivir durante 30 días con su ex mujer, que viene de una larga internación psiquiátrica. La Loba debe hacer la transición entre la internación y su reinserción en la sociedad.', 'uploads/634c9a2b82e768.03583840.mp4', 'Adrián Suar, Luis Bernárdez', 'Adrián Suar, Elisa Carricajo, Elvira Onetto, Jorge Suárez, Laura Paredes, Martín Campilongo, Pichu Straneo, Pilar Gamboa, Rocío Hernández, Valentin We', 2),
(30, 'El Espíritu de Bridge Hollow', 99, 2022, 'uploads/634c9afc901913.49688875.jpg', 'Cuando un malvado espíritu ancestral hace que los adornos de Halloween cobren vida y siembren el caos, un padre (Marlon Wayans) y su hija adolescente (Priah Ferguson) no tienen más remedio que trabajar en equipo para salvar su ciudad.', 'uploads/634c9afc9047c2.97451178.mp4', 'Jeff Wadlow', 'Dave Sheridan, David A. Cooper, Doug Dawson, Gordon Tarpley, Holly J. Barrett, Lauren Lapkus, Marlon Wayans, Nickolas Wolf, Pfeiffer Yaeger, Priah Fer', 2),
(31, 'Together Together', 90, 2021, 'uploads/634c9c82734e33.07878430.jpg', 'Cuando la joven solitaria Anna es contratada como sustituto de Matt, un hombre soltero de unos 40 años, los dos extraños se dan cuenta de que esta relación inesperada desafiará rápidamente sus percepciones de conexión, límites y los detalles del amor.', 'uploads/634c9c827392e3.69913269.mp4', 'Nikole Beckwith', 'Anna Konkle, Ayla Rose Barreau, Bianca Lopez, Caitlin Kimball, Casey Feigh, David Chattam, Ed Helms, Ellen Dubin, Evan Jonigkeit, Fred Melamed, Gail R', 2),
(32, 'Bender: The Beginning', 101, 2021, 'uploads/634c9e3dc9c7e6.70643019.jpg', 'Imperio ruso, 1919. Por un giro del destino, el joven idealista Osip Zadunaisky conoce a un infame estafador y autoproclamado súbdito turco, Ibrahim Bender. Hombre de pensamiento puro y educación aristocrática, Osip nunca se habría asociado con un estafador astuto y sin escrúpulos, pero Bender le hace una oferta que Osip no puede rechazar. Una preciosa reliquia real, un cetro de oro con incrustaciones de diamantes, está escondida en algún lugar de la ciudad; Bender necesita un socio en su misión', 'uploads/634c9e3dca1665.60992415.mp4', 'Igor Zaytsev', 'Aleksandr Aleynov, Aleksandr Ilin, Aleksandr Kakuev, Aleksandr Lapshov, Aleksandr Petrov, Aleksandr Tsekalo, Aleksey Dmitriev, Andrey Pankov, Aram Var', 2),
(33, 'Yo me encargo de la cerveza', 126, 2022, 'uploads/634c9fe2c3ec17.39634082.jpg', 'Nueva York, 1967. Para demostrar su apoyo a sus colegas del barrio que están combatiendo en Vietnam, Chickie Donohue (Zac Efron) decide viajar a la primera línea del frente para llevar a los soldados unas latas de su cerveza norteamericana favorita. Lo que empieza como un viaje repleto de buenas intenciones se convierte rápidamente en una aventura iniciática cuando Chickie se enfrenta a la realidad de esa controvertida guerra, y cuando el reencuentro con sus amigos de la infancia le muestra las ', 'uploads/634c9fe2c40ea1.42500704.mp4', 'Peter Farrelly', 'Archie Renaux, Bill Murray, Christopher Reed Brown, Hal Cumpston, Jake Picking, Joe Adler, Kevin Tran, Kristin Carey, Kyle Allen, MacGregor Arney, Mat', 2),
(34, 'Honor Society', 107, 2022, 'uploads/634ca0d34028c7.57154019.jpg', 'Honor es una ambiciosa estudiante de último año de instituto cuyo único objetivo es entrar en Harvard, suponiendo que primero consiga la codiciada recomendación de su orientador, el Sr. Calvin. Dispuesta a hacer lo que sea necesario, Honor urde un plan maquiavélico para acabar con sus tres principales competidores estudiantiles, hasta que las cosas dan un giro cuando se enamora inesperadamente de su mayor competidor, Michael.', 'uploads/634ca0d3404bd8.86621719.mp4', 'Oran Zegman', 'my Keum, Andres Collantes, Angourie Rice, Armani Jackson, Avery Konrad, Ben Jackson Walker, Christian Lagasse, Christopher Mintz-Plasse, Danny Wattley', 2),
(35, 'Yo era famoso', 114, 2022, 'uploads/634ca1aa1ec1c0.99979430.jpg', 'Vince, una ex estrella del pop desesperada que sueña con regresar. Una improvisada sesión de improvisación con el joven baterista autista Stevie provoca una amistad inesperada entre los dos músicos incomprendidos.', 'uploads/634ca1aa1efd63.94292335.mp4', 'Eddie Sternberg', 'Ed Skrein, Eleanor Matsuura, Eoin Macken, Kurt Egyiawan, Lee Long, Neil Stuke, Racheal Ofori', 2),
(36, 'Good Mourning', 103, 2022, 'uploads/634ca2d00d20b7.03348274.jpg', 'La estrella de cine London Clash ve cómo su mundo se pone patas arriba cuando debe elegir entre perseguir a su único y verdadero amor o conseguir un papel protagonista que le cambiará la vida en una gran película.', 'uploads/634ca2d00d4ad0.09046489.mp4', 'Machine Gun Kelly, Mod Sun', 'Avril Lavigne, Becky G, Boo Johnson, Danny Trejo, Dennis Rodman, Dove Cameron, GaTa, George L. Khouri, Jenna Boyd, Machine Gun Kelly, Megan Fox, Mod S', 2),
(37, 'Viaje al paraiso', 114, 2022, 'uploads/634ca4213955d2.35852827.jpg', 'Una pareja divorciada se une y viaja a Bali para evitar que su hija cometa el mismo error que creen que cometieron hace 25 años.', 'uploads/634ca42139a504.23315600.mp4', 'Ol Parker', 'Billie Lourd, George Clooney, Julia Roberts, Kaitlyn Dever, Lucas Bravo, Maxime Bouttier', 2),
(38, 'Turno del día', 113, 2022, 'uploads/634ca57ee4e8e6.49872353.jpg', 'Tiene una semana para reunir el dinero necesario para pagar las clases y el dentista de su hija. Pero ganarse la vida como cazador de vampiros cada vez es más arriesgado.', 'uploads/634ca57ee52641.73467784.mp4', 'J.J. Perry', 'Angel Nair, C.S. Lee, Danielle Kennedy, Dave Franco, Eric Lange, Jamie Foxx, Karla Souza, Massi Furlan, Meagan Good, Natasha Liu Bordizzo, Oliver Masu', 2),
(39, 'Ex casados', 98, 2021, 'uploads/634ca67a0470e1.88558064.jpg', 'Las diferentes miradas que tiene el matrimonio entre Sonia y Roberto sobre estereotipos, machismo vs feminismo, y cómo quieren vivir sus vidas, los lleva a tomar la decisión de separarse. Luego de dos años se reencuentran para dividir sus bienes. Cada uno con una vida nueva. Sin embargo, un accidente hará que Sonia tenga que ocuparse de cuidar a Roberto, volviendo a convivir en el departamento en el que vivían y viajar juntos al viñedo de sus sueños que tenían en La Rioja.', 'uploads/634ca67a04a0d2.94641843.mp4', 'Sabrina Farji', 'Celina Font, Gabriel Corrado, Jorgelina Aruzzi, Liz Solari, Martín Campilongo, Matías Desiderio, Michel Noher, Roberto Moldavsky', 2),
(40, 'John Wick (Otro día para matar)', 101, 2014, 'uploads/634ca75ade6ce5.08888620.jpg', 'En Nueva York, John Wick, un asesino a sueldo retirado, vuelve otra vez a la acción para vengarse de los gángsters que le quitaron todo.', 'uploads/634ca75adead13.53997641.mp4', 'Chad Stahelski', 'Keanu Reeves,Adrianne Palicki, Alexander Frekey, Alfie Allen.', 3),
(41, 'John Wick 2: Pacto de sangre', 122, 2017, 'uploads/634ca797e4b3c2.39408296.jpg', 'John Wick es forzado a salir del retiro por un ex asociado buscando tomar control del gremio internacional de asesinos. Obligado por un juramento de sangre, Wick viaja a Roma, donde luchará contra algunos de los asesinos más mortales del mundo.', 'uploads/634ca797e4db83.91306588.mp4', 'Chad Stahelski', ' Keanu Reeves, Alessandra Fortuna, Ariane Collman, Chad Stahelski', 3),
(42, 'John Wick 3: Parabellum', 131, 2019, 'uploads/634ca7dda0f8f5.90880849.jpeg', 'John Wick (Keanu Reeves) regresa a la acción, solo que esta vez con una recompensa de 14 millones de dólares sobre su cabeza y con un ejército de mercenarios intentando darle caza. Tras asesinar a uno de los miembros del gremio de asesinos al que pertenecía, Wick es expulsado de la organización, pasando a convertirse en el centro de atención de multitud de asesinos a sueldo que esperan detrás de cada esquina para tratar de deshacerse de él.', 'uploads/634ca7dda15ea5.32049960.mp4', 'Chad Stahelski', ' Keanu Reeves, Andrea Sooch, Anjelica Huston, Arjon Bashiri, Asia Kate Dillon.', 3),
(43, 'Tren Bala', 127, 2022, 'uploads/634ca8fdb33120.14375095.jpg', 'Cinco asesinos a sueldo se encuentran a bordo de un tren bala que viaja de Tokio a Morioka con unas pocas paradas intermedias. Descubren que sus misiones no son ajenas entre sí. La pregunta es quién saldrá vivo del tren y qué les espera en la estación final.', 'uploads/634ca8fdb35ba4.64334757.mp4', 'David Leitch', 'Aaron Taylor-Johnson, Andrea Muñoz Hoyos, Andrew Koji, Bad Bunny, Brad Pitt, Brian Tyree Henry, Channing Tatum, David Leitch, Emelina Adams, Hiroyuki ', 3),
(44, 'The Enforcer', 90, 2022, 'uploads/634ca9e3c45d30.83768415.jpg', 'La película, un thriller negro ambientado en Miami, sigue a un policía que descubre que su jefe, una mujer fatal, se ha convertido en un traficante de sexo, lo que pone en peligro a una joven fugitiva de la que se ha hecho amigo. Sacrifica todo para salvar a la joven de la mortífera organización que se ha pasado la vida construyendo.', 'uploads/634ca9e3c48f51.89422298.mp4', 'Richard Hughes', '2 Chainz, Aaron Cohen, Alexis Ren, Antonio Banderas, Kate Bosworth, Mojean Aria, Natalie Burn, Zolee Griggs', 3),
(45, 'Nitram', 103, 2021, 'uploads/634d3c2ccb4522.39083249.jpg', 'Nitram vive con sus padres en los suburbios de Australia a mediados de los noventa. Vive una vida de aislamiento y frustración por no encajar nunca. A medida que crece su ira, comienza un lento descenso hacia una pesadilla que culmina en los actos más atroces.', 'uploads/634d3c2ccb8688.82538690.mp4', 'Justin Kurzel, Nathan Croft, Oliver Tumm', ' Anita Jenkins, Annabel Marshall-Roth, Anthony LaPaglia, Caleb Landry Jones, Carolyn Hume, Charlotte Friels, Christiana Plitzco, Conrad Brandt, Essie ', 4),
(46, 'El hombre que vendió su piel', 104, 2021, 'uploads/634d3e81179b20.93042759.jpg', 'Sam Ali, un joven sensible e impulsivo de Siria, abandona su país poniendo rumbo hacia el Líbano huyendo de la guerra. Para poder viajar por Europa y vivir así con el amor de su vida, acepta tatuarse la espalda a manos de uno de los artistas contemporáneos más importantes que existen. Tras convertir su cuerpo en una prestigiosa obra de arte, Sam comprende poco a poco que su decisión implica todo lo contrario a lo que él deseaba en un principio: la libertad.', 'uploads/634d3e8117eae4.62543768.mp4', 'Kaouther Ben Hania', 'Adrienne Mei Irving, Alexandre Charlet, Anissa Daoud, Bilel Slim, Christian Vadim, Dana Al Hajji, Darina Al Joundi, Dea Liane, Fayçal Hassaĭri, Husam ', 4),
(47, 'Estamos hechos para entendernos', 93, 2021, 'uploads/634d431b657ef6.73574103.jpg', 'Un profesor de historia de cincuenta años descubre que está perdiendo la audición y comienza a tener una vida de recluso debido a su discapacidad. Su encuentro con Claire, una viuda cuya hija es muda, lo ayudará a abrirse nuevamente al mundo.', 'uploads/634d431b65c589.24063610.mp4', 'Pascal Elbé', 'Anabel Lopez, Anne Azoulay, Antoine Gouy, Atmen Kelif, Benoît Di Marco, Bérangère Mc Neese, Claudia Tagbo, Clémentine Mach, Emmanuelle Devos, Emmanuel', 5),
(48, 'Viaje al paraíso', 94, 2022, 'uploads/634d4665b35a54.86387073.jpg', 'Una pareja divorciada se une y viaja a Bali para evitar que su hija cometa el mismo error que creen que cometieron hace 25 años.', 'uploads/634d4665b399d8.09854214.mp4', 'Ol Parker', 'Billie Lourd, George Clooney, Julia Roberts, Kaitlyn Dever, Lucas Bravo, Maxime Bouttier', 5),
(49, 'First Love', 95, 2022, 'uploads/634d4867dbc640.65740032.jpg', 'La difícil entrada en la vida adulta de un joven que experimenta los altibajos de su primer amor, mientras lidia con las secuelas familiares provocadas por la crisis financiera de 2008.', 'uploads/634d4867dc0062.63223642.mp4', ' A.J. Edwards', 'Diane Kruger, Hero Fiennes-Tiffin, Jeffrey Donovan, Sydney Park', 5),
(50, 'Coco', 105, 2017, 'uploads/634d4c22de1d17.58206265.jpg', '¿Qué pasaría si pudiéramos reencontrarnos con nuestros familiares fallecidos hace tiempo? A partir de la colorida celebración mexicana del Día de los Muertos, Coco nos descubre el misterio de compartir la reunión familiar más extraordinaria y sorprendente, incluso con aquellos antepasados que murieron muchos años atrás. La historia sigue a un niño de doce años de edad llamado Miguel, que vive con su familia en una zona rural de México, y cuyo sueño es la música y tocar la guitarra. Miguel desenc', 'uploads/634d4c22de4fd5.35584477.mp4', 'Adrian Molina, Lee Unkrich', ' Alanna Ubach, Alfonso Aráu, Ana Ofelia Murguía, Anthony Gonzalez, Benjamin Bratt, Blanca Araceli, Cheech Marin, Edward James Olmos, Gabriel Iglesias,', 6),
(51, 'Buscando a Dory', 97, 2016, 'uploads/634d4dc1991e93.21693097.jpg', 'Un año después de los acontecimientos narrados en «Buscando a Nemo», Dory vive apaciblemente con Marlin y su hijo Nemo. Pero durante un viaje para ver cómo las mantarrayas migran de vuelta a casa, los problemas de memoria de Dory parecen desaparecer durante un segundo: recuerda que tiene una familia e inmediatamente decide emprender viaje para reencontrarse con sus padres, a los que perdió hace años.', 'uploads/634d4dc1993818.65794454.mp4', 'Andrew Stanton', 'Albert Brooks, Alexander Gould, Allison Janney, Andrew Stanton, Angus MacLane, Austin Pendleton, Bennett Dammann, Bill Hader, Bob Peterson, Brad Garre', 6),
(52, 'Encanto', 99, 2021, 'uploads/634d4f8a194ab8.20708558.jpg', 'Encanto, te traslada a Colombia, donde una mágica familia vive en una casa llena de magia.', 'uploads/634d4f8a1986f9.40676171.mp4', 'Byron Howard', 'Adassa, Alan Tudyk, Angie Cepeda, Carolina Gaitán, Diane Guerrero, Jessica Darrow, John Leguizamo, Maluma, María Cecilia Botero, Mauro Castillo, Ravi ', 6),
(53, 'Minions: El origen de Gru', 87, 2022, 'uploads/634d523fdb2e34.94427798.jpg', 'Fanboy de un supergrupo de supervillanos conocido como Vicious 6, Gru trama un plan para volverse lo suficientemente malvado como para unirse a ellos, con el respaldo de sus seguidores, los Minions.', 'uploads/634d523fdb6a43.20402621.mp4', ' Brad Ableson', 'Alan Arkin, Colette Whitaker, Danny Trejo, Dolph Lundgren, Jean-Claude Van Damme, Jimmy O. Yang, John DiMaggio, Julie Andrews, Kevin Michael Richardso', 6),
(54, 'Batman y Superman: La batalla de los Sup', 79, 2022, 'uploads/634d537fa57763.86504998.jpg', 'Comienza cuando Jonathan Kent, de once años, descubre que tiene superpoderes, empujando al semi kryptoniano al complicado mundo de los superhéroes y los supervillanos, que ahora están siendo atacados por una fuerza alienígena malvada conocida como Starro”.', 'uploads/634d537fa5bd33.68433797.mp4', 'Matt Peters', 'Darin De Paul, Jack Dylan Grazer, Jack Griffo, Laura Bailey, Myrna Velasco, Nolan North, Tom Kenny, Travis Willingham, Troy Baker, Zeno Robinson', 6),
(55, 'Mi dulce monstruo', 98, 2022, 'uploads/634d548de3e344.26210818.jpeg', 'Un escándalo en la familia real: la descarriada princesa Bárbara escapó del palacio y atravesó el bosque en busca de un apuesto príncipe. Sin embargo, en lugar del preciado encuentro con su amado, es capturada por Buka, el ladrón más peligroso del reino. Pero pronto queda claro que la enérgica princesa está lista para convertir la vida de Buka en una pesadilla, solo para alcanzar su objetivo. Entonces la inquieta Varvara comienza a establecer su propio orden en el bosque.', 'uploads/634d548de42038.86114917.mp4', 'Maksim Volkov', 'Aleksey Chumakov, Alena Doletskaya, Lyubov Aksyonova, Prokhor Chekhovskoy, Pyotr Ivaschenko, Timur Kerimov, Vladislav Kopp', 6),
(56, 'La gallina Turuleca', 80, 2020, 'uploads/634d55f2c4bc00.47314776.jpg', 'Turuleca es una gallina singular. Su peculiar aspecto desata las burlas del resto del gallinero, hasta que un día Isabel, una ex-profesora de música, la lleva a vivir a su granja. Allí, feliz y en armonía, la gallina descubre su gran talento oculto con la ayuda de Isabel: ¡Turuleca no sólo puede hablar, sino que canta como jamás has oído cantar a una gallina!', 'uploads/634d55f2c4fd78.07187467.mp4', 'Eduardo Gondell', 'Álvaro de Juana Pecos, Ana Ángeles García, Eva Hache, José Mota, Paula Coria Portilla', 6),
(57, 'CYRANO', 123, 2022, 'uploads/634d8ede8d0c90.14777497.jpg', 'Película que narrará la vida de Cyrano de Bergerac, novelista y dramaturgo francés del siglo XVII.', 'uploads/634d8ede8d59d5.63822667.mp4', 'Joe Wright', 'Anjana Vasan, Bashir Salahuddin, Ben Mendelsohn, Bettrys Jones, Beverly Rudd, Carl Grose, Celeste Dodwell, Celeste Dring, Colin Mace, Giles King, Glen', 8),
(58, 'Jonas Brothers Family Roast', 68, 2021, 'uploads/634d91615726e0.48432474.jpg', 'Una comedia de humor sobre la banda de pop Jonas Brothers que incluye sketches, canciones, juegos e invitados especiales.\r\n\r\n', 'uploads/634d91615770d5.38632615.mp4', 'Alex Van Wagner', 'Blake Shelton, Danielle Jonas, Gabriel Iglesias, Jack Whitehall, Joe Jonas, John Legend, Kenan Thompson, Kevin Jonas, Lilly Singh, Niall Horan, Nick J', 8),
(59, 'El cover', 90, 2021, 'uploads/634db2a99a5ca8.80696573.jpg', 'Dani es un joven con un gran conflicto interior que le paraliza: ama la música, pero tiene miedo a fracasar como su padre, y sufre pensando que es uno más, como su abuelo, por lo que decide no intentarlo escondiéndose en su autenticidad. Ese verano, entre su trabajo de camarero y las noches con los amigos, conocerá a Sandra. Con ella descubrirá la lucha de los cantantes anónimos, el amor y qué significa no ser uno más.', 'uploads/634db2a99a8798.82838200.mp4', 'Secun de la Rosa', 'Agoney Hernández, Àlex Monner, Ana Hurtado, Antonio Orozco, Belén Bottarini, Benja de la Rosa, Carlos Rivera, Carmen Machi, Carmen Mayordomo, Carolina', 8),
(60, 'Tick, Tick… BOOM!', 121, 2021, 'uploads/634db45368ea61.15348111.jpg', 'En la cúspide de su cumpleaños número 30, un joven y prometedor compositor de teatro navega por el amor, la amistad y las presiones de la vida como artista en la ciudad de Nueva York.', 'uploads/634db453693284.14271600.mp4', 'Josh Muzaffer', 'Adam Pascal, Alex Lacamoire, Alexandra Shipp, Amanda Green, André De Shields, Andrew Garfield, Aneesa Folds, Bebe Neuwirth, Ben Ross, Bernadette Peter', 8),
(61, 'El origen', 148, 2020, 'uploads/634db7c30c77c2.68651566.jpg', 'Dom Cobb (Leonardo DiCaprio) es el mejor extractor. Su oficio consiste en introducirse en los sueños de sus víctimas y extraerle secretos del mundo de los negocios para luego venderlos con grandes dividendos. Debido a sus arriesgados métodos, grandes consorcios lo tienen en la mirilla, y ningún escondite le ofrece seguridad. No puede regresar a los Estados Unidos donde sus hijos le esperan. El empresario Saito (Ken Watanabe) le recluta para su última misión, que de triunfar le podría permitir su', 'uploads/634db7c30cafe2.59765851.mp4', 'Christopher Nolan', 'Leonardo DiCaprio, Marion Cotillard, Elliot Page', 11),
(62, 'Pasaba por aquí', 110, 2022, 'uploads/634dba72a40864.16319087.jpg', 'Un grafitero que tiene como objetivo las casas de la élite descubre un retorcido secreto en un sótano oculto y desata acontecimientos que ponen en peligro a sus seres queridos.', 'uploads/634dba72a428b2.09005618.mp4', 'Babak Anvari', 'Adrian Lane, Alicia Ambrose-Bayly, Amerjit Deu, Antonio Aakeel, Edward Wolstenholme, Fergus Phelan, Gabriel Bisset-Smith, George MacKay, Geraldine Pow', 11),
(63, 'Shutter Island', 137, 2010, 'uploads/634dbc1409fda4.91619171.jpg', 'En 1954 el agente Teddy Daniels (Leonardo DiCaprio) y su compañero Check Aule (Mark Ruffalo) son enviados a la isla de Shutter Island a investigar en un hospital psiquiátrico donde están internados peligrosos criminales. Una de las pacientes, Rachel Solando (Emily Mortimer / Patricia Clarkson), ha desaparecido misteriosamente. ¿Cómo pudo salir de una celda cerrada desde el exterior? El único indicio encontrado en la habitación es un trozo de papel en el que se pueden leer una serie de cifras y l', 'uploads/634dbc140a1fc5.84758360.mp4', 'Martin Scorsese', 'Leonardo DiCaprio, Mark Ruffalo, Ben Kingsley', 11),
(64, 'Contratiempo', 105, 2017, 'uploads/634dbdb5d2f595.39607604.jpg', 'Adrián Doria (Mario Casas) es un exitoso empresario que es acusado de un asesinato, aunque él se declara inocente. Para defenderse, contrata los servicios de la mejor preparadora de testigos del país, Virginia Goodman (Ana Wagener), con quien trabaja una noche para encontrar un argumento que logre liberarle de la cárcel. Pero la aparición de un nuevo testigo de cargo hace peligrar su estrategia, viéndose obligados a recomponer las piezas de un puzle imposible con el tiempo en su contra.\r\n \r\nOrio', 'uploads/634dbdb5d310d6.78287312.mp4', 'Oriol Paulo', 'Ana Wagener, Bárbara Lennie, David Selvas, Francesc Orella, Iñigo Gastesi, José Coronado, Mario Casas, Paco Tous, San Yélamos', 11),
(65, 'El Hobbit (Un viaje inesperado)', 169, 2012, 'uploads/634dc01bbaca50.62193406.jpg', 'Precuela de la trilogía «El Señor de los Anillos», obra de J.R.R. Tolkien. En compañía del mago Gandalf y de trece enanos, el hobbit Bilbo Bolsón emprende un viaje a través del país de los elfos y los bosques de los trolls, desde las mazmorras de los orcos hasta la Montaña Solitaria, donde el dragón Smaug esconde el tesoro de los Enanos. Finalmente, en las profundidades de la Tierra, encuentra el Anillo Único, hipnótico objeto que será posteriormente causa de tantas sangrientas batallas en la Ti', 'uploads/634dc01bbaf131.68562230.mp4', 'Peter Jackson', 'Adam Brown, Aidan Turner, Andy Serkis, Barry Humphries, Benedict Cumberbatch, Billy Connolly, Bret McKenzie, Cate Blanchett, Christopher Lee, Conan St', 12),
(66, 'El Hobbit: La desolación de Smaug', 170, 2013, 'uploads/634dc1eb9112e5.98514559.jpg', 'Tras sobrevivir al inicio de su inesperado viaje, la Compañía sigue hacia el este y se encuentra por el camino con Beorn, el cambiador de piel, y con un enjambre de Arañas gigantes en el peligroso monte Mirkwood. Tras evitar que los Elfos del Bosque los capturen, los Enanos prosiguen su viaje hacia Ciudad del Lago, y finalmente llegan a la Montaña Solitaria, donde tienen que enfrentarse al mayor de los peligros, una criatura más terrorífica que cualquier otra que pondrá a prueba no solo lo profu', 'uploads/634dc1eb913e17.41021875.mp4', 'Carolynne Cunningham', 'Adam Brown, Aidan Turner, Ben Mitchell, Benedict Cumberbatch, Cate Blanchett, Dean O\Gorman, Evangeline Lilly, Graham McTavish, Ian McKellen, James Ne', 12),
(67, 'El señor de los anillos (Las dos torres)', 180, 2002, 'uploads/634dc78cb1dc21.75008816.jpg', 'La Compañía del Anillo se ha disuelto. El portador del anillo Frodo y su fiel amigo Sam se dirigen hacia Mordor para destruir el Anillo Único y acabar con el poder de Sauron. Mientras, y tras la dura batalla contra los orcos donde cayó Boromir, el hombre Aragorn, el elfo Legolas y el enano Gimli intentan rescatar a los medianos Merry y Pipin, secuestrados por los ogros de Mordor. Por su parte, Saurón y el traidor Sarumán continúan con sus planes en Mordor, en espera de la guerra contra las razas', 'uploads/634dc78cb1f859.79171508.mp4', 'Peter Jackson', 'Andy Serkis, Bernard Hill, Billy Boyd, Brad Dourif, Bruce Hopkins, Bruce Phillips, Calum Gittins, Cate Blanchett, Christopher Lee, Craig Parker, David', 12),
(68, 'El señor de los anillos: El retorno del ', 201, 2003, 'uploads/634dc8883bc296.20464504.jpg', 'Las fuerzas de Saruman han sido destruidas, y su fortaleza sitiada. Ha llegado el momento de que se decida el destino de la Tierra Media, y por primera vez en mucho tiempo, parece que hay una pequeña esperanza. La atención del señor oscuro Sauron se centra ahora en Gondor, el último reducto de los hombres, y del cual Aragorn tendrá que reclamar el trono para ocupar su puesto de Rey. Pero las fuerzas de Sauron ya se preparan para lanzar el último y definitivo ataque contra el reino de Gondor, la ', 'uploads/634dc8883c29c7.80306486.mp4', 'Peter Jackson', ' Alistair Browning, Andy Serkis, Bernard Hill, Billy Boyd, Cate Blanchett, Christopher Lee, David Aston, David Wenham, Dominic Monaghan, Elijah Wood, ', 12),
(69, 'Harry Potter y las Reliquias de la Muert', 145, 2010, 'uploads/634dcb415cb4e9.87987771.jpg', 'En esta ocasión, Harry Potter (Daniel Radcliffe) y sus inseparables amigos Ron (Rupert Grint) y Hermione (Emma Watson) tendrán que cargar sobre sus hombros con la tarea más difícil que un mago puede afrontar: destruir los horrocruxes que aún quedan en el mundo para poner fin al reinado de Lord Voldemort (Ralph Fiennes). Harry, Ron y Hermione tienen que recorrer Inglaterra casi a ciegas en busca de los objetos que hacen al Señor Tenebroso más longevo. Pero el poder del lado oscuro no para de aume', 'uploads/634dcb415cd963.75247909.mp4', 'David Yates', 'Adrian Annis, Adrian Rawlins, Afshan Azad, Alan Rickman, Anna Shaffer, Anthony John Crocker, Arben Bajraktaraj, Ashley McGuire, Bill Nighy, Bob Yves V', 12),
(70, 'Harry Potter y las Reliquias de la Muert', 130, 2011, 'uploads/634dcd45d4ad36.24271748.jpg', 'Adrian Rawlins, Afshan Azad, Alan Rickman, Alfie McIlwain, Alfred Enoch, Amber Evans, Anna Shaffer, Anthony Allgood, Arben Bajraktaraj, Ariella Paradise, Arthur Bowen, Ashley McGuire, Benedict Clarke, Benn Northover, Bertie Gilbert, Bob Yves Van Hellenberg Hubar, Bonnie Wright, Chris Rankin, Ciarán Hinds, Clémence Poésy, Daniel Radcliffe, Daphne de Beistegui, Dave Legeno, David Bradley, David Ryall, David Thewlis, Devon Murray, Domhnall Gleeson, Ellie Darcey-Alden, Emil Hostina, Emma Thompson, E', 'uploads/634dcd45d4cd41.68764222.mp4', 'David Yates', ' Adrian Rawlins, Afshan Azad, Alan Rickman, Alfie McIlwain, Alfred Enoch, Amber Evans, Anna Shaffer, Anthony Allgood, Arben Bajraktaraj, Ariella Parad', 12),
(71, 'Harry Potter y el misterio del príncipe', 181, 2009, 'uploads/634dcf0ad13eb1.79513825.jpg', 'En medio de los desastres que azotan a Inglaterra, Harry y sus compañeros vuelven a Hogwarts para cursar su sexto año de estudios; y aunque las medidas de seguridad han convertido al colegio en una fortaleza, algunos estudiantes son víctimas de ataques inexplicables. Harry sospecha que Draco Malfoy es el responsable de los mismos y decide averiguar la razón. Mientras tanto, Albus Dumbledore y el protagonista exploran el pasado de Lord Voldemort mediante recuerdos que el director ha recolectado. ', 'uploads/634dcf0ad1a648.62732239.mp4', 'David Yates', ' Afshan Azad, Alan Rickman, Alfie Enoch, Anna Shaffer, Bonnie Wright, Daniel Radcliffe, Dave Legeno, David Bradley, David Thewlis, Devon Murray, Elari', 12),
(72, 'After Yang', 96, 2022, 'uploads/634dd1a3dc4be9.91973521.jpg', 'Un hombre y su hija intentan salvar por todos los medios posibles la vida de Yang, un robot mitad asistente y mitad niñera, al que consideran un miembro más de su familia.', 'uploads/634dd1a3dc9e30.50755633.mp4', 'Alex Backus, David Ketterer Spencer, Kog', 'Adeline Kerns, Alberto Del Saz, An Li Bogan, Ansley Kerns, Ava DeMary, Brett Dier, Clifton Collins Jr, Colin Farrell, Deborah Hedwall, Eve Lindley, Ha', 13),
(73, 'Jurassic World: Dominion', 147, 2022, 'uploads/634dd372d095d0.08370968.jpg', 'Cuatro años después de la destrucción de Isla Nublar, los dinosaurios conviven – y cazan – con los seres humanos en todo el mundo. Este frágil equilibrio cambiará el futuro y decidirá, de una vez por todas, si los seres humanos seguirán en la cúspide de los depredadores en un planeta que comparten con los animales más temibles de la creación.', 'uploads/634dd372d0e418.30755081.mp4', 'Colin Trevorrow', 'Adam Kiani, Bastian Antonio Fuentes, BD Wong, Bernardo Santos, Bryce Dallas Howard, Campbell Scott, Chris Pratt, Cokey Falkow, Daniella Pineda, DeWand', 13),
(74, 'Programa ADN', 90, 2021, 'uploads/634dd4249d6be0.27416181.jpg', 'Cuando un humilde cartero es incluido en un programa de ADN sobrehumano ultrasecreto en un centro de investigación, se revela que podrá recibir, controlar y enviar información basada en los sentidos de los demás.', 'uploads/634dd4249dbab1.87891403.mp4', 'Martin Grof', 'Alastair G. Cumming, Alex Reid, Anil Desai, Emily Wyatt, Eugene Simon, Jennifer Martin, Kai Francis Lewis, Lorraine Tai, Marybeth Havens', 13),
(75, 'Office Invasion', 112, 2022, 'uploads/634dd556971403.14032095.jpg', 'Tres mejores amigos se unen para defender su valiosa empresa minera de unos monstruosos alienígenas que pretenden saquearla y exterminarla.', 'uploads/634dd556978a94.50760206.mp4', 'Fred Wolmarans, Gareth Crocker', 'Aimee Ntuli, Desmond Dube, Gregg Viljoen, Kiroshan Naidoo, Rea Rangaka, Sechaba Ramphele, Stevel Marc', 13),
(76, 'El equipo redentor', 98, 2022, 'uploads/634df95d590148.03614884.jpg', 'Después de su decepcionante actuación en los Juegos Olímpicos de 2004, el equipo masculino de baloncesto de Estados Unidos busca la redención persiguiendo el oro en Pekín 2008. ', 'uploads/634df95d595f26.42880371.mp4', 'Jon Weinbach', 'Dwyane Wade, LeBron James, Mike Krzyzewski', 14),
(77, 'Obi-Wan Kenobi: El retorno de un jedi', 60, 2022, 'uploads/634df818c2c7f4.67659925.jpg', 'Este especial explora el regreso de Obi-Wan Kenobi y Anakin Skywalker a la pantalla, así como de Ewan McGregor y Hyaden Christensen a sus ya clásicos papeles. La directora Deborah Chow se pone al frente del elenco y del equipo para crear nuevos héroes y villanos, que coexisten con las nuevas reencarnaciones de algunos personajes muy queridos de \"Star Wars\", y para narrar una épica aventura que entronca con las películas de la saga.', 'uploads/634df818c31196.68309082.mp4', 'David Gelb', 'Deborah Chow, Ewan McGregor, Hayden Christensen, Moses Ingram, Vivien Lyra Blair', 14),
(78, 'El misterio de Marilyn Monroe', 101, 2022, 'uploads/634dfbd4488847.17580737.jpg', 'Documental que explora el misterio en torno a la muerte de Marilyn Monroe mediante entrevistas inéditas a su círculo más cercano. Conversaciones con John Huston y la élite de Hollywood ayudan a reconstruir la vida y la muerte de Marilyn Monroe.', 'uploads/634dfbd448cd99.28521686.mp4', 'Emma Cooper', 'Deborah Chow, Ewan McGregor, Hayden Christensen, Moses Ingram, Vivien Lyra Blair', 14),
(80, '1917', 120, 2019, 'uploads/634df5171c9821.39919828.jpg', 'Nos encontramos en el año 1917. La Guerra Mundial amenazaba con cambiar, para siempre, el orden mundial. Ante la amenaza que se cernía, Estados Unidos decidió entrar en el conflicto con el objetivo de desequilibrar la balanza que caracterizaba a la contienda.', 'uploads/634df5171cc831.82859287.mp4', 'Sam Mendes', 'Adrian Scarborough, Andrew Scott, Benedict Cumberbatch, Billy Postlethwaite, Chris Walley, Claire Duburcq, Colin Firth, Daniel Mays, Dean-Charles Chap', 16),
(81, 'Hasta el ultimo hombre', 139, 2016, 'uploads/634df6a3662cc4.59789178.jpg', 'Narra la historia de Desmond Doss, un joven médico militar que participó en la batalla de Okinawa, en el Pacífico durante la II Guerra Mundial, y se convirtió en el primer objetor de conciencia en la historia estadounidense en recibir la Medalla de Honor del Congreso.', 'uploads/634df6a3667944.71391704.mp4', 'Jo Weeks, Mel Gibson, P.J. Voeten, Sophi', 'Andrew Garfield, Ben Mingay, Ben O\Toole, Benedict Hardie, Bill Young, Charles Jacobs, Damien Thomlinson, Dennis Kreusler, Firass Dirani, Goran D. Kle', 16),
(82, 'Dunkirk (Dunkerque)', 107, 2017, 'uploads/634df74d37f941.93657256.jpg', 'Cuando 400.000 hombres no pudieron regresar a casa... su hogar fue a buscarlos.\r\nDunkerque comienza con cientos de miles de soldados del ejército británico y las tropas aliadas rodeados por el enemigo. Atrapados en la playa con el mar a sus espaldas, se enfrentan a una situación imposible en la que el enemigo los tiene encerrados.\r\n\r\nLa historia transcurre por tierra, mar y aire. Los Spitfire de la RAF se enfrentan al enemigo en el cielo sobre el Canal para tratar de proteger a los indefensos ho', 'uploads/634df74d386882.74670852.mp4', 'Alexis Chelli, Alina Gatti, Amaury Capel', 'Adam Long, Aldo Beqiri, Aneurin Barnard, Barry Keoghan, Bill Milner, Billy Howle, Bobby Lockwood, Bradley Hall, Bram Vlot, Brandon Duracher, Brian Ver', 16),
(83, 'Against the Sun', 100, 2014, 'uploads/634df7d5a95bc9.10135532.jpg', 'Dirigida por Brian Falk y guión escrito por Mark David Keegan y el propio Falk. Inspirada en una historia real que está escrita en la novela \'The Raft\' de Robert Trumbull. Este drama bélico cuenta la historia de un piloto de la Segunda Guerra Mundial es derribado durante un ataque. Junto con él, caen también un bombardero y un operador de radio. Rodeados de agua en el Pacífico Sur, consigue salvar sus vidas gracias a una pequeña balsa. Sin embargo, no tienen comida ni agua. Sin nadie que los res', 'uploads/634df7d5a9a7f9.61479850.mp4', 'Brian Falk, Jose Jimenez, Kari Montgomer', 'Garret Dillahunt, Jake Abel, Nadia Parra, Tom Felton', 16),
(84, 'Harry Potter, 20º Aniversario: Regreso ', 90, 2022, 'uploads/634dfc3531a9a8.17711883.jpg', 'Daniel Radcliffe, Rupert Grint y Emma Watson se unen al cineasta Chris Columbus y a otros queridos miembros del reparto de las ocho películas de Harry Potter en su viaje de regreso a Hogwarts por primera vez para celebrar el aniversario de la primera película de la franquicia, Harry Potter y la piedra filosofal, que se estrenó hace 20 años. El especial retrospectivo Harry Potter 20th Anniversary: Return to Hogwarts contará una historia encantadora.', 'uploads/634dfc3531ee33.20454552.mp4', 'Eran Creev', 'Alfonso Cuarón, Alfred Enoch, Bonnie Wright, Chris Columbus, Daniel Radcliffe, David Heyman, David Yates, Emma Watson, Evanna Lynch, Gary Oldman, Hele', 14);

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `peliculas`
--
ALTER TABLE `peliculas`
  ADD PRIMARY KEY (`id`),
  ADD KEY `id_genero` (`id_genero`);

--
-- AUTO_INCREMENT de las tablas volcadas
--

--
-- AUTO_INCREMENT de la tabla `peliculas`
--
ALTER TABLE `peliculas`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=86;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
